lib/rules/node-param-description-unneeded-backticks.ts, package.json, tests/node-param-description-unneeded-backticks.test.ts
=> Fix uneeded backticks autofix

docs/rules/cred-class-field-name-unsuffixed.md, docs/rules/cred-class-field-name-uppercase-first-char.md, docs/rules/cred-class-name-unsuffixed.md, docs/rules/node-param-array-type-assertion.md, docs/rules/node-param-color-type-unused.md, docs/rules/node-param-default-missing.md, docs/rules/node-param-description-excess-inner-whitespace.md, docs/rules/node-param-description-missing-final-period.md, docs/rules/node-param-description-unneeded-backticks.md, docs/rules/node-param-display-name-lowercase-first-char.md, docs/rules/node-param-display-name-miscased.md, lib/rules/node-param-description-excess-inner-whitespace.ts, lib/rules/node-param-description-missing-final-period.ts, lib/rules/node-param-description-unneeded-backticks.ts, lib/rules/node-param-display-name-lowercase-first-char.ts, lib/rules/node-param-display-name-miscased.ts, lib/utils/getters/nodeParam.ts, lib/utils/identifiers/nodeParam.ts, lib/utils/index.ts, tests/node-param-default-missing.test.ts, tests/node-param-description-excess-inner-whitespace.test.ts, tests/node-param-description-missing-final-period.test.ts, tests/node-param-description-unneeded-backticks.test.ts, tests/node-param-display-name-lowercase-first-char.test.ts, tests/node-param-display-name-miscased.test.ts
=> Adjustments from creds run

docs/rules/node-param-description-miscased-id.md, lib/constants.ts, lib/rules/node-param-description-miscased-id.ts, lib/rules/node-param-display-name-miscased-id.ts, tests/node-param-description-miscased-id.test.ts
=> Fix ID capitalization autofix

README.md, docs/rules/node-param-default-wrong-for-number.md, lib/rules/node-param-default-wrong-for-number.ts, tests/node-param-default-wrong-for-number.test.ts
=> Loosen number type param default check

docs/rules/node-param-default-wrong-for-string.md, lib/rules/node-param-default-wrong-for-string.ts, tests/node-param-default-wrong-for-string.test.ts
=> Except string-type param with array default

lib/rules/node-param-collection-type-unsorted-items.ts, lib/rules/node-param-fixed-collection-type-unsorted-items.ts, lib/rules/node-param-multi-options-type-unsorted-items.ts, lib/rules/node-param-options-type-unsorted-items.ts, lib/utils/format.ts, lib/utils/index.ts
=> Fix formatting for `options` and `multiOptions` params

lib/utils/getters/_restore.ts, lib/utils/getters/nodeParam.ts, lib/utils/identifiers/nodeParam.ts, tests/node-param-default-missing.test.ts
=> Fix negative number handling in `node-param-default-missing`

docs/rules/node-param-placeholder-miscased-id.md, lib/rules/node-param-placeholder-miscased-id.ts, tests/node-param-placeholder-miscased-id.test.ts
=> Tolerate cases in `node-param-placeholder-miscased-id`

docs/rules/node-param-default-wrong-for-simplify.md, lib/utils/identifiers/nodeParam.ts, tests/node-param-default-wrong-for-simplify.test.ts
=> Tighten Simplify param check

docs/rules/node-class-description-display-name-unsuffixed-trigger-node.md, lib/rules/node-class-description-display-name-unsuffixed-trigger-node.ts, tests/node-class-description-display-name-unsuffixed-trigger-node.test.ts
=> Tolerate `(Beta)` suffix

lib/constants.ts, package.json
Ref: https://github.com/n8n-io/n8n/pull/3716
=> Update expressions docs URL

lib/rules/node-resource-description-filename-against-convention.ts, package-lock.json, package.json
=> Fix resource description filename detection

lib/constants.ts, lib/rules/node-param-collection-type-unsorted-items.ts, lib/rules/node-param-fixed-collection-type-unsorted-items.ts, lib/rules/node-param-multi-options-type-unsorted-items.ts, lib/rules/node-param-options-type-unsorted-items.ts
=> Do not sort numeric strings

package.json
=> Match ESLint version with n8n

lib/ast/getters/credentialClassBody.getters.ts, lib/ast/index.ts, lib/ast/utils/index.ts, lib/ast/utils/restoreValue.ts, lib/rules/cred-class-field-display-name-missing-oauth2.ts, lib/rules/cred-class-field-name-missing-oauth2.ts, lib/rules/cred-class-name-missing-oauth2-suffix.ts, lib/types.ts, package.json
=> Migrate away from restorers

docs/rules/node-param-display-name-miscased-id.md, lib/rules/node-param-display-name-miscased-id.ts, tests/node-param-display-name-miscased-id.test.ts
Ref: https://n8nio.slack.com/archives/D038X76GWTW/p1671091200536419
=> Add exception for expression in miscased ID rule

.github/workflows/on-push.yml, .github/workflows/test-lint-codebase-command.yml, lint-codebase-config.js, scripts/lint-codebase.sh
=> Re-fix `lint-codebase` command

.github/workflows/on-push.yml
https://github.blog/changelog/2020-04-15-github-actions-sets-the-ci-environment-variable-to-true/
=> Remove `CI: true`

.vscode/settings.json, README.md, docs/rules/cred-class-field-type-options-password-missing.md, docs/rules/node-param-type-options-password-missing.md, lib/rules/cred-class-field-type-options-password-missing.ts, lib/rules/node-param-type-options-password-missing.ts, scratchpad/.eslintrc.js, scratchpad/README.md, scratchpad/sample/nodes/Sample/Sample.node.ts, tests/cred-class-field-type-options-password-missing.test.ts, tests/node-param-type-options-password-missing.test.ts
=> fix: Edge cases in password-field-checking rules

package.json, scripts/track-pending-rules.mjs
=> ci: Track pending rules

README.md, docs/rules/node-param-collection-type-unsorted-items.md, lib/rules/node-param-collection-type-unsorted-items.ts, tests/node-param-collection-type-unsorted-items.test.ts
=> chore: Remove broken autofix for `node-param-collection-type-unsorted-items`
